# Generated by Django 3.0.8 on 2020-07-29 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('opening_crawl', models.TextField()),
                ('director', models.CharField(max_length=255)),
                ('producers', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gravity', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('movies', models.ManyToManyField(to='graphQLStartwars.Movie')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='planets',
            field=models.ManyToManyField(to='graphQLStartwars.Planet'),
        ),
    ]
